### ISSUE TITLE
这不是我想象的结果。。。。

### ISSUE THREAD

**Issue by jiazufei** [ianisme/CoolNavi#1]
![1111](https://cloud.githubusercontent.com/assets/3351691/9806549/863a2260-5878-11e5-9d86-de2ad44bfa41.gif)

**Comment by jiazufei** [comment]
自动弹回来了，demo中没问题
放到我的工程里就这样了，奇怪啊

**Comment by ianisme** [comment]
@jiazufei 您仔细看看我的代码，这种情况和contentsize有关

**Comment by ianisme** [comment]
@jiazufei 您在TableView中填满数据就不会出现问题了

**Comment by jiazufei** [comment]
好的，我看看
我想说的是，代码没做过任何改变啊

**Comment by jiazufei** [comment]
需要填充满整个视图吗

**Comment by jiazufei** [comment]
果然，要填充满表格，谢谢

**Comment by ianisme** [comment]
你把cell数据加上就ok了，因为tableView的contentsize不够，所以会弹回来

**Comment by ianisme** [comment]
@jiazufei 不客气
