### ISSUE TITLE
请问updateSubViewsWithScrollOffset:方法中

### ISSUE THREAD

**Issue by iamjjh** [ianisme/CoolNavi#2]
titleDestinateOffset这项属性是什么意思？为什么等于self.frame.size.height-40

**Comment by ianisme** [comment]
@iamjjh 这是屏幕显示子视图的偏移量，您将此值设置为self.frame.size.height 会发现子视图会在原地不动。

**Comment by iamjjh** [comment]
请问为什么是-40?

**Comment by ianisme** [comment]
@iamjjh 因为我为了让头像显示在导航栏那个位置

**Comment by iamjjh** [comment]
明白了，多谢解答
